#!/usr/bin/env python
# -*-coding:utf-8-*-
import pygame

pygame.init()

gameDisplay=pygame.display.set_mode((800,600))

x=80
y=0
xc=0
xy=0


clock=pygame.time.Clock()
running=True

walist = [(0,0,40,600),
          (41,570,850,40)]

while running:
    for event in pygame.event.get():
        if event.type==pygame.QUIT:
            pygame.quit()
            quit()
        if event.type == pygame.KEYDOWN:
            if event.key==pygame.K_LEFT:
                xc -= 1
            if event.key==pygame.K_RIGHT:
                xc += 1
            if event.key==pygame.K_UP:
                xy -= 1
            if event.key==pygame.K_DOWN:
                xy += 1
        if event.type == pygame.KEYUP:
            if event.key == pygame.K_LEFT:
                xc=0
            if event.key == pygame.K_RIGHT:
                xc=0
            if event.key==pygame.K_UP:
                xy = 0
            if event.key==pygame.K_DOWN:
                xy = 0
                
    gameDisplay.fill((0,0,0))
    
    x+=xc
    y+=xy
    
    rect1= pygame.Rect (x,y,10,20)
    pygame.draw.rect(gameDisplay, (255,255,255) , rect1)
    
    for qq in walist:
        wally=pygame.Rect(qq)
        wally1=pygame.Rect(qq)
        pygame.draw.rect(gameDisplay, (0,255,255) , wally)
        pygame.draw.rect(gameDisplay, (0,255,255) , wally1)
    
    
    if rect1.colliderect(wally):
        x=50
        y=50
    if rect1.colliderect(wally1):
        x=50
        y=50
    pygame.display.update()
    
    clock.tick(120)
        
